version: '3.9'
services:
  proxy:
    image: nginx
    volumes:
      - ./volume/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./volume/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 88:80
  app:
    image: node
    volumes:
      - ./volume/node/:/node
    ports:
      - 3000:3000
    entrypoint: "node /node/index.js"